### ISSUE TITLE
Chat GPT token exposed

### ISSUE THREAD

**Issue by carotm** [robusta-dev/kubernetes-chatgpt-bot#18]
If you open slack in a browser you can easily see chat_gtp_token
<img width="1766" alt="token" src="https://user-images.githubusercontent.com/29898948/234683601-2e2967e8-2973-49c0-b8ab-9a5441cb9a00.png">

I think it's safer to remove `chat_gpt_token` from the Action Params and read the token from an environment variable. Also, the environment variable can be added using the value of the chart `runner.additional_env_vars`  value, example:
```
runner:
  additional_env_vars:
  - name: OPENAI_API_KEY
    value: 
```
